apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-port
      protocol: TCP
  selector:
    app: keycloak-db
#  type: LoadBalancer