apiVersion: v1
kind: Service
metadata:
  name: wso2-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql-port
      protocol: TCP
  selector:
    app: wso2-db
#  type: LoadBalancer