apiVersion: v1
kind: Service
metadata:
  name: wso2
  labels:
    app: wso2
spec:
  ports:
    - name: webconsole
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: api_http
      port: 8280
      targetPort: 8280
      protocol: TCP
    - name: api_https
      port: 8243
      targetPort: 8243
      protocol: TCP
  selector:
    app: wso2
#  type: LoadBalancer